import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth.service';
import { PlantingApiService, type PlantingDetails } from '../../core/planting-api.service';

@Component({
 selector:'dv-planting-details',imports:[RouterLink],
 template:`<section class="screen"><header class="hero compact"><div class="hero-top"><a class="back" routerLink="/planting">‹</a><div><div class="brand">DRAGON-VIEW</div><h1>Planting Group Details</h1></div><span></span></div></header><div class="content">
 @if(group();as g){<article class="card panel"><div class="section-heading"><h2>#{{g.recordNumber}}</h2><span class="badge">{{stageLabel(g)}}</span></div><div class="facts"><div><small>Variety</small><b>{{g.variety}}</b></div><div><small>Location</small><b>{{g.location}}</b></div><div><small>Plants</small><b>{{g.numberOfPlants}}</b></div><div><small>Grafted</small><b>{{g.graftingDate}}</b></div><div><small>Maturity</small><b>{{g.estimatedMaturityDate}}</b></div><div><small>Remaining</small><b>{{g.remainingDays}} days</b></div></div><div class="progress"><span [style.width.%]="g.progressPercent"></span></div></article>
 <article class="card panel"><h2>Add Monitoring Note</h2><form (submit)="monitor($event)"><textarea name="notes" maxlength="500" required placeholder="Observations for this planting group"></textarea><button>Save note</button></form></article>
 @if(isOwner()){<article class="card panel"><h2>Owner/Admin Actions</h2><form class="edit" (submit)="update($event)"><input name="graftingDate" type="date" [value]="g.graftingDate" [max]="today" required><input name="variety" [value]="g.variety" required><input name="location" [value]="g.location" required><input name="plants" type="number" min="1" [value]="g.numberOfPlants" required><button>Save changes</button></form><button class="delete" (click)="remove()">Soft delete group</button></article>}
 <div class="section-heading heading"><h2>Monitoring History</h2><span>Newest first</span></div><div class="record-list">@for(note of g.monitoring;track note.id){<article class="card note"><strong>{{note.recordedBy}}</strong><small>{{note.recordedAt}}</small><p>{{note.notes}}</p></article>}@empty{<article class="card note">No monitoring notes yet.</article>}</div>
 }@else{<article class="card panel">{{message()||'Loading…'}}</article>}@if(message()){<p class="message">{{message()}}</p>}</div></section>`,
 styles:`.compact{padding-bottom:22px}.back{color:white;text-decoration:none;font-size:30px}.panel,.note{padding:20px;margin-bottom:14px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.facts div{display:grid;gap:4px}.facts small,.note small{color:var(--muted)}.progress{height:10px;margin-top:18px;border-radius:10px;background:var(--line);overflow:hidden}.progress span{display:block;height:100%;background:var(--magenta)}form{display:grid;gap:9px}.edit{grid-template-columns:repeat(2,1fr)}input,textarea{padding:11px;border:1px solid var(--line);border-radius:10px;font:inherit}textarea{min-height:90px}button{padding:11px;border:0;border-radius:10px;color:white;background:var(--magenta);font-weight:800}.delete{margin-top:12px;background:var(--red)}.heading{margin-top:20px}.message{color:var(--magenta)}@media(max-width:600px){.facts,.edit{grid-template-columns:1fr 1fr}}`,
 changeDetection:ChangeDetectionStrategy.OnPush
})
export class PlantingDetailsComponent{
 private readonly api=inject(PlantingApiService);private readonly auth=inject(AuthService);private readonly router=inject(Router);private readonly id=Number(inject(ActivatedRoute).snapshot.paramMap.get('id'));protected readonly group=signal<PlantingDetails|null>(null);protected readonly message=signal('');protected readonly today=new Date().toISOString().slice(0,10);protected readonly isOwner=()=>this.auth.user()?.role==='OWNER_ADMIN';
 constructor(){this.load()}protected stageLabel(g:PlantingDetails){return g.readyForHarvest?'Ready for Harvest':g.stage.replaceAll('_',' ')}
 protected monitor(e:SubmitEvent){e.preventDefault();const f=e.currentTarget as HTMLFormElement;if(!f.reportValidity())return;const d=new FormData(f);this.api.monitor(this.id,String(d.get('notes'))).subscribe({next:()=>{f.reset();this.message.set('Monitoring note saved.');this.load()},error:()=>this.message.set('Unable to save note.')})}
 protected update(e:SubmitEvent){e.preventDefault();const f=e.currentTarget as HTMLFormElement;if(!f.reportValidity())return;const d=new FormData(f);this.api.update(this.id,{graftingDate:d.get('graftingDate'),variety:d.get('variety'),location:d.get('location'),numberOfPlants:Number(d.get('plants'))}).subscribe({next:()=>{this.message.set('Planting group updated.');this.load()},error:()=>this.message.set('Unable to update group.')})}
 protected remove(){const reason=window.prompt('Reason for removing this planting group:')?.trim();if(!reason)return;this.api.remove(this.id,reason).subscribe({next:()=>void this.router.navigateByUrl('/planting'),error:()=>this.message.set('Unable to remove group.')})}
 private load(){this.api.details(this.id).subscribe({next:({data})=>this.group.set(data),error:()=>this.message.set('Planting group could not be loaded.')})}
}
