import { CurrencyPipe, DatePipe, DecimalPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DashboardApiService, type DashboardData } from '../../core/dashboard-api.service';

@Component({
 selector:'dv-dashboard',imports:[RouterLink,CurrencyPipe,DatePipe,DecimalPipe],
 template:`<section class="screen"><header class="hero"><div class="hero-top"><span></span><div><div class="brand">DRAGON-VIEW</div><h1>Dashboard</h1></div><button class="refresh" (click)="load()" [disabled]="loading()">↻ Refresh</button></div></header>
 <div class="content">@if(data();as dashboard){
  <div class="section-heading"><h2>Farm Overview</h2><span>Live operational data</span></div>
  <div class="metric-grid dashboard-metrics">@for(metric of metrics();track metric.label){<a class="card metric-card metric-link" [routerLink]="metric.route"><div class="row"><span class="metric-icon" [style.color]="metric.color" [style.background]="metric.soft">{{metric.icon}}</span><span class="badge">{{metric.badge}}</span></div><div class="metric-value">{{metric.currency?(metric.value|currency:'PHP':'symbol-narrow'):(metric.value|number)}}</div><div class="metric-label">{{metric.label}}</div></a>}</div>
  <div class="dashboard-grid"><section class="card chart-card"><div class="section-heading"><div><h3>Harvest Trend</h3><p>Last 7 days · registered pieces</p></div><a routerLink="/harvests">View harvests</a></div><div class="bar-chart">@for(day of trend();track day.date){<div class="bar-column"><span class="bar-value">{{day.pieces}}</span><span class="bar" [style.height.%]="barHeight(day.pieces)"></span><small>{{day.date|date:'EEE'}}</small></div>}</div></section>
  <section class="card chart-card"><div class="section-heading"><div><h3>Classification Results</h3><p>Last 7 days</p></div><a routerLink="/classification">Open history</a></div><div class="quality-layout"><div class="donut" [style.background]="donutBackground()"><strong>{{classificationTotal()}}</strong><small>results</small></div><ul>@for(grade of gradeRows();track grade.grade){<li><i [class]="'grade-'+grade.grade.toLowerCase()"></i><span><b>Grade {{grade.grade}}</b><small>{{grade.name}}</small></span><strong>{{grade.count}} · {{grade.percent|number:'1.0-0'}}%</strong></li>}</ul></div></section></div>
  <div class="section-heading activity-heading"><h2>Recent Activity</h2><span>Newest records</span></div><div class="activity-grid">
    <section class="card activity"><h3>Inventory</h3>@for(item of dashboard.recent.inventory;track item.id){<a [routerLink]="['/inventory',item.id]"><span>{{item.label}}</span><small>{{item.type.replaceAll('_',' ')}} · {{item.pieces>0?'+':''}}{{item.pieces}}</small></a>}@empty{<p>No inventory activity.</p>}</section>
    <section class="card activity"><h3>Sales</h3>@for(item of dashboard.recent.sales;track item.id){<a [routerLink]="['/sales',item.id]"><span>{{item.label}}</span><small>{{item.type}} · {{item.amount|currency:'PHP':'symbol-narrow'}}</small></a>}@empty{<p>No sales activity.</p>}</section>
    <section class="card activity"><h3>Planting</h3>@for(item of dashboard.recent.planting;track item.id){<a [routerLink]="['/planting',item.id]"><span>#{{item.label}}</span><small>{{item.amount}} plants</small></a>}@empty{<p>No planting records.</p>}</section>
    <section class="card activity"><h3>Classification</h3>@for(item of dashboard.recent.classifications;track item.id){<a routerLink="/classification"><span>{{item.label}}</span><small>{{item.amount*100|number:'1.0-1'}}% confidence</small></a>}@empty{<p>No classifications.</p>}</section>
  </div>
  <section class="quick-actions"><a routerLink="/harvests" [queryParams]="{add:1}">Record harvest</a><a routerLink="/sales/new">New sale</a><a routerLink="/planting">Monitor plants</a><a routerLink="/classification">Classify fruit</a></section>
 }@else{<article class="card state">{{error()||'Loading dashboard…'}}</article>}</div></section>`,
 styles:`.refresh{position:relative;z-index:1;padding:9px 13px;border:1px solid #ffffff33;border-radius:10px;color:white;background:#ffffff18;font-weight:700;cursor:pointer}.metric-link{color:inherit;text-decoration:none}.dashboard-metrics{grid-template-columns:repeat(3,1fr)}.dashboard-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.section-heading a{color:var(--magenta);font-size:12px;text-decoration:none;font-weight:700}.bar-chart{height:200px;display:grid;grid-template-columns:repeat(7,1fr);gap:8px;align-items:end;border-bottom:1px solid var(--line)}.bar-column{height:100%;display:flex;flex-direction:column;justify-content:end;align-items:center;gap:4px}.bar{width:55%;min-height:3px;border-radius:8px 8px 2px 2px;background:linear-gradient(var(--magenta),#ef6c99)}.bar-value,.bar-column small{font-size:10px;color:var(--muted)}.quality-layout{display:grid;grid-template-columns:150px 1fr;gap:22px;align-items:center}.donut{aspect-ratio:1;display:grid;place-content:center;position:relative;border-radius:50%}.donut:after{content:'';position:absolute;inset:25%;border-radius:50%;background:white}.donut strong,.donut small{position:relative;z-index:1;text-align:center}.quality-layout ul{display:grid;gap:12px;padding:0;list-style:none}.quality-layout li{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center}.quality-layout li i{width:10px;height:10px;border-radius:50%}.quality-layout li span{display:grid}.quality-layout small,.activity small{color:var(--muted)}.grade-a{background:var(--green)}.grade-b{background:var(--amber)}.grade-c{background:var(--red)}.activity-heading{margin-top:24px}.activity-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.activity{padding:18px}.activity h3{margin-top:0}.activity a{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-top:1px solid var(--line);color:inherit;text-decoration:none}.activity p{color:var(--muted)}.quick-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.quick-actions a{padding:13px;border-radius:12px;color:white;background:var(--magenta);text-align:center;text-decoration:none;font-weight:700}.state{padding:24px}@media(max-width:1000px){.dashboard-metrics{grid-template-columns:repeat(2,1fr)}.dashboard-grid{grid-template-columns:1fr}.quick-actions{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.dashboard-metrics,.activity-grid{grid-template-columns:1fr 1fr}.quality-layout{grid-template-columns:110px 1fr}.quick-actions{grid-template-columns:1fr 1fr}}`,
 changeDetection:ChangeDetectionStrategy.OnPush
})
export class DashboardComponent{
 private readonly api=inject(DashboardApiService);protected readonly data=signal<DashboardData|null>(null);protected readonly loading=signal(false);protected readonly error=signal('');
 protected readonly classificationTotal=computed(()=>{const g=this.data()?.classificationByGrade;return g?g.A+g.B+g.C:0});private readonly maxHarvest=computed(()=>Math.max(1,...this.trend().map(d=>d.pieces)));
 protected readonly metrics=computed(()=>{const s=this.data()?.summary;if(!s)return[];return[
  {value:s.inventoryPieces,label:'Inventory pieces',icon:'▣',badge:'Available',color:'#8f2aaa',soft:'#f1e5f5',route:'/inventory',currency:false},
  {value:s.activeBatches,label:'Active harvest batches',icon:'▤',badge:'FIFO',color:'#f2a526',soft:'#fff3d9',route:'/inventory',currency:false},
  {value:s.salesToday,label:"Today's completed sales",icon:'₱',badge:'Today',color:'#60ae55',soft:'#e8f5e5',route:'/sales',currency:false},
  {value:s.monthlyRevenue,label:'Monthly revenue',icon:'↗',badge:'This month',color:'#d32366',soft:'#fde9f0',route:'/analytics',currency:true},
  {value:s.plantingGroups,label:'Planting groups monitored',icon:'⚘',badge:'Active',color:'#60ae55',soft:'#e8f5e5',route:'/planting',currency:false},
  {value:s.classificationsToday,label:'Classifications today',icon:'A',badge:'Today',color:'#e44e4e',soft:'#fde8e8',route:'/classification',currency:false}]});
 constructor(){this.load()}protected load(){this.loading.set(true);this.error.set('');this.api.load().subscribe({next:({data})=>{this.data.set(data);this.loading.set(false)},error:()=>{this.error.set('Dashboard data could not be loaded.');this.loading.set(false)}})}
 protected trend(){const rows=this.data()?.harvestTrend??[];const byDate=new Map(rows.map(r=>[String(r.date).slice(0,10),r.pieces]));return Array.from({length:7},(_,i)=>{const d=new Date();d.setUTCDate(d.getUTCDate()-(6-i));const date=d.toISOString().slice(0,10);return{date,pieces:byDate.get(date)??0}})}
 protected barHeight(value:number){return Math.max(2,value/this.maxHarvest()*100)}protected gradeRows(){const g=this.data()?.classificationByGrade??{A:0,B:0,C:0},t=this.classificationTotal();return[{grade:'A',name:'Good Quality',count:g.A,percent:t?g.A/t*100:0},{grade:'B',name:'OK',count:g.B,percent:t?g.B/t*100:0},{grade:'C',name:'Blemished',count:g.C,percent:t?g.C/t*100:0}]}
 protected donutBackground(){const rows=this.gradeRows(),a=rows[0].percent,b=a+rows[1].percent;return`conic-gradient(var(--green) 0 ${a}%,var(--amber) ${a}% ${b}%,var(--red) ${b}% 100%)`}
}
